export const priorities = [
  {value: 1, description: 'ASAP'},
  {value: 2, description: '12 weeks before the event'},
  {value: 3, description: '8 weeks before the event'},
  {value: 4, description: '4 weeks before the event'},
  {value: 5, description: '3 weeks before the event'},
  {value: 6, description: '2 weeks before the event'},
  {value: 7, description: '1 Week before the event'},
  {value: 8, description: '5 days before the event'},
  {value: 9, description: '4 days before the event'},
  {value: 10, description: '3 days before the event'},
  {value: 11, description: '2 days before the event'},
  {value: 12, description: '1 days before the event'},
  {value: 13, description: 'Day of the event'},
  {value: 14, description: 'After the event'},
]