name: Deploy Site to Demo
on: workflow_dispatch
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Debugging - List files in root directory
      run: ls -l
    - name: Select environment file
      run: cp .env.demo .env
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run production
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.mgsmusic.co.nz
        username: activityHubDemoDeploy@activityhub.co.nz
        password: ActivityHubGitHub
