name: Build and Deploy Site on push
on:
  push:
    branches:
      - master
jobs:
  build:
    # name: Deploy
    runs-on: ubuntu-latest
      
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    
    - name: Installing project dependencies
      run: npm install
      
    - name: Building the project
      run: npm run production
      
    # - name: Copy .env
    #  run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    # - name: Install lftp
    #  run: sudo apt-get install lftp -y

  deploy:
    runs-on: ubuntu-latest

    needs: build

    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

    steps:
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.FTP_SERVER }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        # server: ftp.mgsmusic.co.nz
        # username: activityhubDeploy@mgsmusic.co.nz
        # password: ActivityHubGitHub
